### ISSUE TITLE
Doesn't work in WINE

### ISSUE THREAD

**Issue by raymoo** [shiburizu/concerto-mbaacc#9]
Concerto can open cccaster but isn't able to control it (or that's what it looks like). The cccaster window stays doing nothing and options can be selected normally like if I had launched it by itself.

Steps to reproduce:
0. Be using WINE on Linux
1. Run Concerto
2. Navigate and select Training
3. Wait for cccaster to open
4. Wait for something to happen

**Comment by raymoo** [comment]
Here is the console output if it helps:
```
  japanese wine Concerto
[INFO   ] [Logger      ] Record log in C:\users\webble\.kivy\logs\kivy_21-08-17_3.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\users\webble\Temp\_MEI432\kivy\__init__.pyc"
[INFO   ] [Python      ] v3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "Z:\home\webble\games\melty\japanese\Concerto.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
002e:err:module:import_dll Library gstreamer-1.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
002e:err:module:import_dll Library glib-2.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
002e:err:module:import_dll Library gobject-2.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
[INFO   ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3 (Compatibility Profile) Mesa 20.3.4'>
[INFO   ] [GL          ] OpenGL vendor <b'nouveau'>
[INFO   ] [GL          ] OpenGL renderer <b'NV117'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [Factory     ] Ignored class "MenuBtn" re-declaration. Current -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\Concerto.kv. Ignored -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\concerto.kv.
[WARNING] [Factory     ] Ignored class "PlayerRow" re-declaration. Current -  module: None, cls: None, baseclass: AnchorLayout, filename: C:\users\webble\Temp\_MEI432\Concerto.kv. Ignored -  module: None, cls: None, baseclass: AnchorLayout, filename: C:\users\webble\Temp\_MEI432\concerto.kv.
[WARNING] [Factory     ] Ignored class "DummyBtn" re-declaration. Current -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\Concerto.kv. Ignored -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\concerto.kv.
[WARNING] [Factory     ] Ignored class "LobbyBtn" re-declaration. Current -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\Concerto.kv. Ignored -  module: None, cls: None, baseclass: Button, filename: C:\users\webble\Temp\_MEI432\concerto.kv.
[WARNING] [Factory     ] Ignored class "OptionRow" re-declaration. Current -  module: None, cls: None, baseclass: BoxLayout, filename: C:\users\webble\Temp\_MEI432\Concerto.kv. Ignored -  module: None, cls: None, baseclass: BoxLayout, filename: C:\users\webble\Temp\_MEI432\concerto.kv.
[INFO   ] [GL          ] NPOT texture support is available
002e:err:module:import_dll Library gstreamer-1.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
002e:err:module:import_dll Library glib-2.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
002e:err:module:import_dll Library gobject-2.0-0.dll (which is needed by L"C:\\users\\webble\\Temp\\_MEI432\\kivy\\lib\\gstplayer\\_gstplayer.cp38-win_amd64.pyd") not found
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[WARNING] [Concerto    ] argv is Z:\home\webble\games\melty\japanese\Concerto.exe
[WARNING] [Concerto    ] PATH is Z:\home\webble\games\melty\japanese\
[INFO   ] [Base        ] Start application main loop
 Exception in thread Thread-2:
 Traceback (most recent call last):
   File "threading.py", line 932, in _bootstrap_inner
   File "threading.py", line 870, in run
   File "mbaacc.py", line 414, in local
     con = self.aproc.read()
   File "winpty\ptyprocess.py", line 192, in read
 EOFError: Pty is closed
[INFO   ] [Base        ] Leaving application in progress...
Error: Could not find process "cccaster.v3.0.exe".
Error: Could not find process "cccaster.v3.0.exe".
[WARNING] [Concerto    ] old CWD is Z:\home\webble\games\melty\japanese
[WARNING] [Concerto    ] new CWD is Z:\home\webble\games\melty\japanese
```

The warnings about gstreamer are because I disabled it to avoid a crash on melty title screen (which can appear briefly when cccaster launches melty)

EDIT: Here is the full log file https://paste.debian.net/1208140/

**Comment by shiburizu** [comment]
Concerto is not compatible with WINE for the following reasons:

1. Concerto depends on [tasklist](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tasklist) to monitor MBAACC & CCCaster processes. WINE [does not implement this at all in the main branch](https://github.com/wine-mirror/wine/blob/master/programs/tasklist/tasklist.c), and a [staging version of this](https://github.com/wine-staging/wine-staging/blob/master/patches/tasklist-basics/0001-tasklist.exe-add-minimal-functionality.patch) is missing most of the functionality including some that we depend on.
2. [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/) provides "pseudo terminals" to the[ pywinpty library](https://github.com/spyder-ide/pywinpty) that is used to control CCCaster in the background. While WINE release notes mention [ConPTY support since 5.18](https://www.winehq.org/announce/5.18) in practice it produces incorrect behavior: as noted in your report a visible terminal is spawned and Concerto cannot send or receive information to it. 

Both of these inconsistencies are grounds for bug reports to the WINE developers. Assuming nobody else does this before me I will do so with the release of a 1.0 version. However due to the nature of the problem (entirely missing features in WINE) I must close this as wontfix.
